[package]
name = "simple"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[dependencies]
inherit-derive = { path = "../../inherit-derive" }
inherit = { path = "../../inherit" }
